### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ghost** [DevMakerMobileApps/handbook#10]
no arquivo https://github.com/DevMakerMobileApps/handbook/blob/main/job_posts/programmer.md
na segunda vez o endereço de email tá errado

![Screenshot_20220425-171033~2](https://user-images.githubusercontent.com/10067116/165167203-51193048-2874-4909-8352-c32ccf979485.png)

**Comment by Rudiney** [comment]
Obrigado @otofonte!
